# United Software
IMPORT_FOEDUS_PROGRAMME_SOONG_NAMESPACES ?= false

# Accord
TARGET_INCLUDE_ACCORD ?= true
ifeq ($(TARGET_INCLUDE_ACCORD),true)
PRODUCT_PACKAGES += \
    Accord

IMPORT_FOEDUS_PROGRAMME_SOONG_NAMESPACES := true
endif

# Gramophone
TARGET_INCLUDE_GRAMOPHONE ?= true
ifeq ($(TARGET_INCLUDE_GRAMOPHONE),true)
PRODUCT_PACKAGES += \
    Gramophone

IMPORT_FOEDUS_PROGRAMME_SOONG_NAMESPACES := true
endif

# Omni
TARGET_INCLUDE_OMNI ?= true
ifeq ($(TARGET_INCLUDE_OMNI),true)
PRODUCT_PACKAGES += \
    Omni

IMPORT_FOEDUS_PROGRAMME_SOONG_NAMESPACES := true
endif

# Soong
ifeq ($(IMPORT_FOEDUS_PROGRAMME_SOONG_NAMESPACES),true)
PRODUCT_SOONG_NAMESPACES += \
    $(PARASITE_PREBUILTS)/common/FoedusProgramme
endif
